name: Github Actions CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1

    - name: Say Hello!
      run: echo Hello world! 

    - name: Compile Example
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        working_directory: example

    - name: Check pdf files
      run: |
        file example/main.pdf | grep -q ' PDF '

    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: main
        path: example
      if: always()
